FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY ./modules/KafkaModule/requirements.txt ./
RUN pip install -r requirements.txt

COPY ./src/FirstEdgeSolution/modules/KafkaModule .

CMD [ "python3", "-u", "./KafkaModule.py" ]